<?php

/**
 * @file
 * This is the file description for Remove Menu Path module.
 *
 * In this more verbose, multi-line description, you can specify what this
 * file does exactly. Make sure to wrap your documentation in column 78 so
 * that the file can be displayed nicely in default-sized consoles.
 */

/**
 * Implementation of hook_menu_alter.
 *
 */
function remove_menu_path_menu_alter(&$items) {
  // Gives "drupal not found" at URL/node.
  $items['node']['page callback'] = 'drupal_not_found';
}